experiment_name: "simclr/cifar10"

method_type: "simclr"

dataset:
  name: "cifar10"
  path: "./data/"

training:
  batch_size: 64
  num_epochs: 100
  lr: 0.5
  save_every: 10
  augmentations_type: "cifar"
  augment_both: True

model:
  encoder_type: "resnet50"
  pretrained: False
  width_multiplier: 4
  hidden_dim: 2048
  projection_dim: 128

loss:
  temperature: 0.5