experiment_name: "simclr/cifar10"

method_type: "simclr"

dataset:
  name: "cifar10"
  path: "./data/"

training:
  batch_size: 512
  num_epochs: 1000
  lr: 0.5
  save_every: 100
  augmentations_type: "cifar"
  augment_both: True
  track_performance: False

model:
  encoder_type: "resnet50"
  pretrained: False
  width_multiplier: 2
  hidden_dim: 2048
  projection_dim: 128

loss:
  temperature: 0.1

evaluation:
  K: [5, 10, 20]
  checkpoints_dir: "experiments/simclr/cifar10/checkpoints/"
  KNN_eval: False
  TSNE_plot: True